use std::{env, fs, path::PathBuf};

fn main() {
    let manifest  = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let notes_dir = manifest.join("../notes");
    let out_file  = PathBuf::from(env::var("OUT_DIR").unwrap()).join("notes_data.rs");

    // Collect all .md files, sorted
    let mut paths: Vec<String> = vec![];
    if notes_dir.is_dir() {
        collect(&notes_dir, &notes_dir, &mut paths);
    }
    paths.sort();

    // Generate static array of (path, content) pairs.
    // Each content is embedded via include_str! at compile time.
    let mut code = String::from("// auto-generated by build.rs — do not edit\n");
    code.push_str("pub static NOTES: &[(&str, &str)] = &[\n");

    for rel in &paths {
        // Use forward slashes for web paths; include_str! needs the actual OS path
        let rel_fwd = rel.replace('\\', "/");
        // Build the include_str! path using CARGO_MANIFEST_DIR so it works from any cwd
        code.push_str(&format!(
            "  ({rel_fwd:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../notes/{rel_fwd}\"))),\n"
        ));
        // Tell Cargo to re-run build.rs when this specific note changes
        println!("cargo:rerun-if-changed=../notes/{rel_fwd}");
    }

    code.push_str("];\n");

    fs::write(&out_file, code).expect("write notes_data.rs");

    // Re-run if new files are added to the notes directory
    println!("cargo:rerun-if-changed=../notes");
    println!("cargo:rerun-if-changed=build.rs");
}

fn collect(base: &PathBuf, dir: &PathBuf, out: &mut Vec<String>) {
    let Ok(rd) = fs::read_dir(dir) else { return };
    let mut entries: Vec<_> = rd.filter_map(|e| e.ok()).collect();
    entries.sort_by_key(|e| e.file_name());
    for entry in entries {
        let p = entry.path();
        if p.is_dir() {
            collect(base, &p, out);
        } else if p.extension().and_then(|e| e.to_str()) == Some("md") {
            if let Ok(rel) = p.strip_prefix(base) {
                out.push(rel.to_string_lossy().into_owned());
            }
        }
    }
}
