// Embedded note index — generated by build.rs from the ../notes/ directory.
// Rebuilds automatically when any .md file changes or new files are added.
include!(concat!(env!("OUT_DIR"), "/notes_data.rs"));
// Expands to: pub static NOTES: &[(&str, &str)] = &[("path.md", "content"), ...];

use std::{cell::RefCell, rc::Rc};
use wasm_bindgen::{prelude::*, JsCast, JsValue};
use web_sys::{Document, Element, HtmlInputElement};

// ── state ──────────────────────────────────────────────────────────────

struct State {
    current: Option<usize>, // index into NOTES
    query:   String,
}

// ── public handle (cheaply cloneable via Rc) ───────────────────────────

#[derive(Clone)]
pub struct Notes {
    inner: Rc<Inner>,
}

struct Inner {
    panel:  Element,
    tree:   Element,
    body:   Element,
    title:  Element,
    search: HtmlInputElement,
    state:  RefCell<State>,
}

impl Notes {
    pub fn init(doc: &Document) -> Result<Self, String> {
        let notes = Notes {
            inner: Rc::new(Inner {
                panel:  get_el(doc, "notes-panel")?,
                tree:   get_el(doc, "notes-tree")?,
                body:   get_el(doc, "notes-body")?,
                title:  get_el(doc, "notes-title")?,
                search: doc
                    .get_element_by_id("notes-search")
                    .ok_or("no #notes-search")?
                    .dyn_into::<HtmlInputElement>()
                    .map_err(|_| "not an input")?,
                state:  RefCell::new(State { current: None, query: String::new() }),
            }),
        };
        notes.wire_search();
        notes.wire_tree();
        notes.wire_body();
        Ok(notes)
    }

    pub fn show(&self) {
        let _ = self.inner.panel.class_list().remove_1("notes-hidden");
        self.render_tree();
        let current = self.inner.state.borrow().current;
        // If no note selected yet, default to the first one.
        let idx = current.unwrap_or(0);
        self.open_idx(idx);
    }

    pub fn hide(&self) {
        let _ = self.inner.panel.class_list().add_1("notes-hidden");
    }

    // ── tree ───────────────────────────────────────────────────────────

    fn render_tree(&self) {
        let state = self.inner.state.borrow();
        let html = build_tree_html(&state.query);
        self.inner.tree.set_inner_html(&html);
        if let Some(idx) = state.current {
            mark_active(&self.inner.tree, NOTES[idx].0);
        }
    }

    fn open_idx(&self, idx: usize) {
        if idx >= NOTES.len() { return; }
        let (path, raw) = NOTES[idx];
        let title = extract_title(raw, path);
        let md    = preprocess(raw);
        let html  = render_md(&md);
        self.inner.body.set_inner_html(&html);
        self.inner.title.set_text_content(Some(&title));
        call_scramble_notes_body();
        self.inner.state.borrow_mut().current = Some(idx);
        mark_active(&self.inner.tree, path);
    }

    fn open_by_path(&self, path: &str) {
        if let Some(idx) = NOTES.iter().position(|(p, _)| *p == path) {
            self.open_idx(idx);
        }
    }

    fn open_by_name(&self, name: &str) {
        let nl = name.to_lowercase();
        if let Some(idx) = NOTES.iter().position(|(p, _)| {
            p.rsplit('/').next()
                .unwrap_or(p)
                .trim_end_matches(".md")
                .to_lowercase() == nl
        }) {
            self.open_idx(idx);
        }
    }

    // ── event wiring ───────────────────────────────────────────────────

    fn wire_search(&self) {
        let n     = self.clone();
        let input = self.inner.search.clone();
        let cb = Closure::wrap(Box::new(move |_: web_sys::InputEvent| {
            n.inner.state.borrow_mut().query = input.value();
            n.render_tree();
        }) as Box<dyn FnMut(web_sys::InputEvent)>);
        let _ = self.inner.search
            .add_event_listener_with_callback("input", cb.as_ref().unchecked_ref());
        cb.forget();
    }

    fn wire_tree(&self) {
        let n = self.clone();
        let cb = Closure::wrap(Box::new(move |e: web_sys::MouseEvent| {
            let el = match e.target().and_then(|t| t.dyn_into::<Element>().ok()) {
                Some(el) => el,
                None => return,
            };
            let cl = el.class_list();
            if cl.contains("tree-file") {
                if let Some(path) = el.get_attribute("data-path") {
                    n.open_by_path(&path);
                }
            } else if cl.contains("tree-dir") {
                if let Some(children) = el.next_element_sibling() {
                    let scl = children.class_list();
                    let dir = el.get_attribute("data-dir").unwrap_or_default();
                    if scl.contains("tree-collapsed") {
                        let _ = scl.remove_1("tree-collapsed");
                        el.set_text_content(Some(&format!("▾ {dir}/")));
                    } else {
                        let _ = scl.add_1("tree-collapsed");
                        el.set_text_content(Some(&format!("▸ {dir}/")));
                    }
                }
            }
        }) as Box<dyn FnMut(web_sys::MouseEvent)>);
        let _ = self.inner.tree
            .add_event_listener_with_callback("click", cb.as_ref().unchecked_ref());
        cb.forget();
    }

    fn wire_body(&self) {
        let n = self.clone();
        let cb = Closure::wrap(Box::new(move |e: web_sys::MouseEvent| {
            let mut cur = e.target().and_then(|t| t.dyn_into::<Element>().ok());
            while let Some(el) = cur {
                if el.tag_name().eq_ignore_ascii_case("A") {
                    if let Some(href) = el.get_attribute("href") {
                        if href.starts_with("wiki://") {
                            e.prevent_default();
                            let name = href[7..].replace("%20", " ");
                            n.open_by_name(&name);
                            return;
                        }
                    }
                }
                cur = el.parent_element();
            }
        }) as Box<dyn FnMut(web_sys::MouseEvent)>);
        let _ = self.inner.body
            .add_event_listener_with_callback("click", cb.as_ref().unchecked_ref());
        cb.forget();
    }
}

// ── file tree HTML ─────────────────────────────────────────────────────

fn build_tree_html(query: &str) -> String {
    if NOTES.is_empty() {
        return r#"<div class="notes-empty">// NO NOTES FOUND<br>// ADD .MD FILES TO notes/<br>// THEN REBUILD</div>"#.into();
    }

    let mut out = String::new();

    if !query.is_empty() {
        let ql = query.to_lowercase();
        let hits: Vec<_> = NOTES.iter()
            .filter(|(p, _)| p.to_lowercase().contains(&ql))
            .collect();
        if hits.is_empty() {
            return r#"<div class="notes-empty">// no results</div>"#.into();
        }
        for (path, _) in hits {
            let name = file_stem(path);
            out.push_str(&format!(r#"<div class="tree-file" data-path="{path}">⎯&nbsp;{name}</div>"#));
        }
        return out;
    }

    // Grouped by top-level directory
    let mut roots: Vec<&str>  = vec![];
    let mut dirs: std::collections::BTreeMap<&str, Vec<&str>> = std::collections::BTreeMap::new();

    for (path, _) in NOTES {
        match path.find('/') {
            Some(slash) => dirs.entry(&path[..slash]).or_default().push(path),
            None        => roots.push(path),
        }
    }

    for path in roots {
        let name = file_stem(path);
        out.push_str(&format!(r#"<div class="tree-file" data-path="{path}">⎯&nbsp;{name}</div>"#));
    }

    for (dir, children) in &dirs {
        out.push_str(&format!(r#"<div class="tree-dir" data-dir="{dir}">▸&nbsp;{dir}/</div>"#));
        out.push_str(&format!(r#"<div class="tree-children tree-collapsed" data-parent="{dir}">"#));
        for path in children {
            let name = path.rsplit('/').next().map(|n| n.trim_end_matches(".md")).unwrap_or(path);
            out.push_str(&format!(r#"<div class="tree-file" data-path="{path}">⎯&nbsp;{name}</div>"#));
        }
        out.push_str("</div>");
    }

    out
}

fn file_stem(path: &str) -> &str {
    path.rsplit('/').next().unwrap_or(path).trim_end_matches(".md")
}

fn mark_active(tree: &Element, path: &str) {
    if let Ok(Some(prev)) = tree.query_selector(".tree-file.active") {
        let _ = prev.class_list().remove_1("active");
    }
    let safe = path.replace('\'', "\\'");
    if let Ok(Some(el)) = tree.query_selector(&format!(".tree-file[data-path='{safe}']")) {
        let _ = el.class_list().add_1("active");
        // Auto-expand the parent directory if it's collapsed
        if let Some(parent) = el.parent_element() {
            if parent.class_list().contains("tree-children") {
                let _ = parent.class_list().remove_1("tree-collapsed");
                if let Some(dir_el) = parent.previous_element_sibling() {
                    if let Some(dir_name) = dir_el.get_attribute("data-dir") {
                        dir_el.set_text_content(Some(&format!("▾ {dir_name}/")));
                    }
                }
            }
        }
    }
}

// ── markdown pipeline ──────────────────────────────────────────────────

fn preprocess(raw: &str) -> String {
    wiki_links(strip_frontmatter(raw))
}

fn strip_frontmatter(s: &str) -> &str {
    if let Some(rest) = s.strip_prefix("---") {
        if let Some(end) = rest.find("\n---") {
            return rest[end + 4..].trim_start();
        }
    }
    s
}

fn wiki_links(md: &str) -> String {
    let mut out = String::with_capacity(md.len() + 64);
    let mut chars = md.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '[' && chars.peek() == Some(&'[') {
            chars.next();
            let mut link = String::new();
            let mut closed = false;
            loop {
                match chars.next() {
                    Some(']') if chars.peek() == Some(&']') => { chars.next(); closed = true; break; }
                    Some(c2) => link.push(c2),
                    None     => break,
                }
            }
            if closed && !link.is_empty() {
                let enc = link.replace(' ', "%20");
                out.push_str(&format!("[{link}](wiki://{enc})"));
            } else {
                out.push_str("[[");
                out.push_str(&link);
            }
        } else {
            out.push(c);
        }
    }
    out
}

fn render_md(md: &str) -> String {
    use pulldown_cmark::{html, Options, Parser};
    let opts = Options::ENABLE_TABLES
        | Options::ENABLE_STRIKETHROUGH
        | Options::ENABLE_TASKLISTS
        | Options::ENABLE_FOOTNOTES;
    let mut out = String::new();
    html::push_html(&mut out, Parser::new_ext(md, opts));
    out
}

fn extract_title(raw: &str, path: &str) -> String {
    if let Some(rest) = raw.strip_prefix("---") {
        if let Some(end) = rest.find("\n---") {
            for line in rest[..end].lines() {
                if let Some(v) = line.strip_prefix("title:") {
                    let t = v.trim().trim_matches('"').trim_matches('\'');
                    if !t.is_empty() { return t.to_uppercase(); }
                }
            }
        }
    }
    for line in strip_frontmatter(raw).lines() {
        if let Some(h) = line.strip_prefix("# ") {
            let t = h.trim();
            if !t.is_empty() { return t.to_uppercase(); }
        }
    }
    path.rsplit('/').next().unwrap_or(path)
        .trim_end_matches(".md")
        .replace('-', " ")
        .replace('_', " ")
        .to_uppercase()
}

fn get_el(doc: &Document, id: &str) -> Result<Element, String> {
    doc.get_element_by_id(id).ok_or_else(|| format!("#{id} not found"))
}

fn call_scramble_notes_body() {
    let Some(win) = web_sys::window() else { return };
    let Ok(val)   = js_sys::Reflect::get(&win, &JsValue::from_str("__scrambleNotesBody")) else { return };
    if let Some(f) = val.dyn_ref::<js_sys::Function>() {
        let _ = f.call0(&JsValue::NULL);
    }
}
